# Generated by Django 4.0.4 on 2023-04-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('koelkast', '0001_initial_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='interval',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='input',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask'),
        ),
        migrations.AddField(
            model_name='output',
            name='interval',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='output',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='koelkast.output'),
        ),
    ]
